import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home page",
  description: "Generated by create next app",
  keywords: ["next", "create", "nextjs"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="h-[50px] z-10 bg-blue-400 p-4 items-center border sticky top-0">
          <h1>Header</h1>
        </header>
        {children}
        <footer className="h-[100px] bg-blue-400">
          <h1>Footer</h1>
        </footer>
        </body>
    </html>
  );
}
